### PR TITLE
retrieve spark driver logs and log them in airflow in case of app failure

### PR DESCRIPTION
**Pull request by tcassou**
This is related to the discussion started in [#4672225](https://support.spot.io/hc/requests/4672225) with some improvement ideas for this Airflow operator.

# Motivation & Context
In the current implementation, the only logs provided by the operator are about the application URL in the console, and the task status. Logs from a typical Airflow job will look like:

```
[2024-08-31, 12:45:16 UTC] {operators.py:148} INFO - App submitted with app_id: xxx-yyy-zzz
[2024-08-31, 12:45:17 UTC] {operators.py:156} INFO - View app details at https://full.app.url/and/params/here
[2024-08-31, 12:45:17 UTC] {operators.py:167} INFO - spark-run in app state: PENDING
[2024-08-31, 12:45:17 UTC] {operators.py:168} INFO - Sleeping for 10 seconds.
...
[2024-08-31, 12:45:27 UTC] {operators.py:156} INFO - View app details at https://full.app.url/and/params/here
[2024-08-31, 12:45:27 UTC] {operators.py:167} INFO - spark-run in app state: RUNNING
[2024-08-31, 12:45:27 UTC] {operators.py:168} INFO - Sleeping for 10 seconds.
...
[2024-08-31, 12:45:48 UTC] {operators.py:156} INFO - View app details at https://full.app.url/and/params/here
[2024-08-31, 12:47:11 UTC] {operators.py:159} INFO - spark-run completed successfully.
...
```

When a job succeeds, one rarely needs to go and check Spark logs. When a job fails though, it means checking Airflow logs won't be enough, and one has to login to the Spot console and check Spark driver logs there. This may sound like not much, but when done frequently (for example in the context of iteratively developing new apps), it quickly adds up and creates a bit of friction.

This PR proposes to automatically fetch and dump driver logs from the Ocean Spark API in case of app failures, so that they become available in Airflow. 

Airflow logs in case of app failure would now typically look like: 

```
[2024-08-31, 12:45:16 UTC] {operators.py:148} INFO - App submitted with app_id: xxx-0ba41-studs
[2024-08-31, 12:45:17 UTC] {operators.py:156} INFO - View app details at https://full.app.url/and/params/here
[2024-08-31, 12:45:17 UTC] {operators.py:167} INFO - spark-run in app state: PENDING
[2024-08-31, 12:45:17 UTC] {operators.py:168} INFO - Sleeping for 10 seconds.
...
[2024-08-31, 12:45:27 UTC] {operators.py:156} INFO - View app details at https://full.app.url/and/params/here
[2024-08-31, 12:45:27 UTC] {operators.py:167} INFO - spark-run in app state: RUNNING
[2024-08-31, 12:45:27 UTC] {operators.py:168} INFO - Sleeping for 10 seconds.
...
[2024-08-31, 12:47:27 UTC] Ocean Spark task failure, retrieving Spark driver logs...
24/08/31 12:45:29 INFO SparkContext: Running Spark version 3.5.1
24/08/31 12:45:29 INFO SparkContext: Submitted application: inc-load-taggings
24/08/31 12:45:31 INFO SparkEnv: Registering BlockManagerMaster
2024-08-31T12:45:22.434924514Z
2024-08-31T12:45:22.434927854Z Traceback (most recent call last):
2024-08-31T12:45:22.434931134Z   File "/opt/spark/work-dir/main.py", line 82, in <module>
2024-08-31T12:45:22.434934383Z     raise ProcessingError("Error processing one or more tables.")
2024-08-31T12:45:22.434937463Z __main__.ProcessingError: Error processing one or more tables.
24/08/31 12:45:57 INFO ShutdownHookManager: Shutdown hook called
```

# About this implementation
* fetching logs from the [`/live` endpoint](https://docs.spot.io/api/#tag/Ocean-Spark/operation/OceanSparkClusterApplicationIssuesList) as when testing, I found that the [`/archive` endpoint](https://docs.spot.io/api/#tag/Ocean-Spark/operation/OceanSparkClusterApplicationLogsArchive) would return 404s as the zip file was not ready for download yet 
* I had to move `json` deserialization out of the `_do_api_call` method of the `OceanSparkHook` class, as the new endpoint responds with content-type `text/plain`
* `requests` mock URIs were a bit too permissive due to the catch-all `.*` which also captures `/`, meaning that mocking an endpoint that's strictly contained in another endpoint would not work and the wrong mock response could be returned. The new `[^\/]*` pattern prevents that by allowing anything but a `/`

# Checklist
- [x] all linters, type checks and tests pass locally (`make all-tests`)
- [x] tests added to validate the new behaviour

### CODE REVIEW

**Comment by thorsteinnth** [comment]
Thank you for the PR @tcassou!

Please sign and submit [NetApp's Corporate Contributor License Agreement (CCLA)](https://netapp.tap.thinksmart.com/prod/Portal/ShowWorkFlow/AnonymousEmbed/3d2f3aa5-9161-4970-997d-e482b0b033fa). 

- For project name in the dropdown, you can select 'other' 
- In project name you can set 'ocean-spark-airflow-provider'
- In project website you can put https://github.com/spotinst/ocean-spark-airflow-provider

**Comment by sigmarkarl** [comment]
Looks good, only concern is if there is a problem with printing huge driver logs from long running applications

**Comment by tcassou** [comment]
> Looks good, only concern is if there is a problem with printing huge driver logs from long running applications

Thanks for your feedback! Good point, I'd suggest to print only the last `N` lines of logs then, with a reasonable value? Errors - which we're interested in -  are going to be located towards the end of the the driver logs.

**Comment by sigmarkarl** [comment]
> > Looks good, only concern is if there is a problem with printing huge driver logs from long running applications
> 
> Thanks for your feedback! Good point, I'd suggest to print only the last `N` lines of logs then, with a reasonable value? Errors - which we're interested in - are going to be located towards the end of the the driver logs.

Or just have a configuration flag to enable printing the logs. 
If we are printing out the last N lines, perhaps optionally also dump the whole logs to a file somewhere (if it is more accessible than accessing the logs from the console, just thoughts).

**Comment by tcassou** [comment]
> Or just have a configuration flag to enable printing the logs.
If we are printing out the last N lines, perhaps optionally also dump the whole logs to a file somewhere (if it is more accessible than accessing the logs from the console, just thoughts).

I'm tempted to start very simple since we're not retrieving anything right now, and explore more subtle behaviours next based on needs?

so maybe both a flag as you suggested + a high enough limit just to be safe, could be a reasonable start?

**Comment by sigmarkarl** [comment]
> > Or just have a configuration flag to enable printing the logs.
> > If we are printing out the last N lines, perhaps optionally also dump the whole logs to a file somewhere (if it is more accessible than accessing the logs from the console, just thoughts).
> 
> I'm tempted to start very simple since we're not retrieving anything right now, and explore more subtle behaviours next based on needs?
> 
> so maybe both a flag as you suggested + a high enough limit just to be safe, could be a reasonable start?

Sounds good

**Comment by tcassou** [comment]
Hi @sigmarkarl, I've just pushed an update based on the above discussion. Thanks!

**Review by sigmarkarl — DISMISSED** [review]

**Comment by tcassou** [comment]
I've just realized that the "max size" setting I introduced probably does not make sense yet - I had in mind to keep N log lines, but as is it's actually dealing with characters. 
I'll take another look and will provide a more meaningful value.

**Comment by tcassou** [comment]
@thorsteinnth @sigmarkarl FYI I've pushed 6f0876edc3e82aeab566e07eb330aa79f9fe176a.
In the spirit of starting simple, and because truncating logs would imply introducing some heuristics to get a reasonable amount of lines (no possibility to sort/paginate when calling the API) I've only kept the operator flag (what you were suggesting initially).

I would expect API failures (e.g. timeouts) before print failures if the logs are too big anyway.

**Comment by thorsteinnth** [comment]
Hey @tcassou, thanks for this!

A quick reminder to please sign and submit [NetApp's Corporate Contributor License Agreement (CCLA)](https://netapp.tap.thinksmart.com/prod/Portal/ShowWorkFlow/AnonymousEmbed/3d2f3aa5-9161-4970-997d-e482b0b033fa).

For project name in the dropdown, you can select 'Ocean-spark-airflow-provider'

**Comment by tcassou** [comment]
> A quick reminder to please sign and submit [NetApp's Corporate Contributor License Agreement (CCLA)](https://netapp.tap.thinksmart.com/prod/Portal/ShowWorkFlow/AnonymousEmbed/3d2f3aa5-9161-4970-997d-e482b0b033fa).

I just submitted the form ✅

**Review by sigmarkarl — APPROVED** [review]

**Review by alextarasov-spot — APPROVED** [review]

**Pull request merged**
